import { Spacing } from '@/constants/Spacing';
import { StyleSheet } from 'react-native';
import { Colors } from 'react-native/Libraries/NewAppScreen';

const gameStyles = StyleSheet.create({
	errorContainer: {
		flex: 1,
		justifyContent: 'center',
		alignItems: 'center',
		backgroundColor: Colors.mainBackground,
		padding: Spacing.large,
		textAlign: 'center',
	},
	gameScreenContainer: {
		flex: 1,
		backgroundColor: Colors.mainBackground,
		paddingHorizontal: Spacing.large,
		paddingTop: Spacing.large,
	},
	errorMessageText: {
		fontSize: 20,
		fontWeight: 'bold',
		color: Colors.error,
		marginBottom: Spacing.medium,
		textAlign: 'center',
		lineHeight: 28,
	},
	errorMessageSubText: {
		fontSize: 16,
		color: Colors.textSecondary,
		marginBottom: Spacing.small,
		textAlign: 'center',
	},
	restartButtonText: {
		fontSize: 18,
		fontWeight: 'bold',
		color: Colors.primary,
		marginTop: Spacing.medium,
		textDecorationLine: 'underline',
	},
	scoreBoardWrapper: {
		flexDirection: 'row',
		justifyContent: 'space-around',
		alignItems: 'center',
		backgroundColor: Colors.mainBackground,
		borderRadius: Spacing.borderRadius,
		marginVertical: Spacing.medium,
		padding: Spacing.medium,
		shadowColor: Colors.shadow,
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.1,
		shadowRadius: 3,
		elevation: 3,
		borderColor: Colors.border,
		borderWidth: 1,
	},
	modalOverlay: {
		flex: 1,
		justifyContent: 'center',
		alignItems: 'center',
		backgroundColor: Colors.modalBackground,
	},
	modalContent: {
		margin: Spacing.large,
		backgroundColor: Colors.mainBackground,
		borderRadius: Spacing.borderRadius * 2,
		padding: Spacing.xlarge,
		alignItems: 'center',
		shadowColor: Colors.shadow,
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.25,
		shadowRadius: 4,
		elevation: 5,
		width: '80%',
		maxWidth: 400,
	},
	modalHintText: {
		marginBottom: Spacing.large,
		textAlign: 'center',
		fontSize: 18,
		fontWeight: 'bold',
		color: Colors.textPrimary,
		lineHeight: 24,
	},
	modalButton: {
		backgroundColor: Colors.primary,
		paddingVertical: Spacing.medium,
		paddingHorizontal: Spacing.large,
		borderRadius: Spacing.borderRadius,
		marginTop: Spacing.medium,
		shadowColor: Colors.shadow,
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.2,
		shadowRadius: 3,
		elevation: 5,
	},
	modalButtonText: {
		color: Colors.buttonText,
		fontSize: 16,
		fontWeight: 'bold',
	},
});

export default gameStyles;
